name: Mi primera automatizacion

on:
  workflow_dispatch:

jobs:
  saludar:
    runs-on: ubuntu-latest

    steps:
      - name: Decir hola
        run: echo "Hola! GitHub acaba de ejecutar mi primera automatizacion"
